"""sync server defaults for exchange_integrations and user_credentials

Revision ID: b18870aaa923
Revises: 0005
Create Date: 2026-08-17 12:59:26.010414+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b18870aaa923'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange_integrations', 'exchange',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_credentials', 'environment',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_credentials', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_credentials', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('user_credentials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_credentials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_credentials', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_credentials', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'ACTIVE'::character varying"),
               existing_nullable=False)
    op.alter_column('user_credentials', 'environment',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'DEMO'::character varying"),
               existing_nullable=False)
    op.alter_column('exchange_integrations', 'exchange',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'OKX'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
